using System.Collections.Generic;
using UnityEngine;

namespace Platformer.Mechanics
{
    /// <summary>
    /// Runtime mapping from a worker's display name to the animator controller that drives
    /// that family member's walking / idle animation. Generated by SetupFamilyAnimations.
    /// </summary>
    [CreateAssetMenu(fileName = "FamilyAnimationConfig", menuName = "Game/Family Animation Config")]
    public class FamilyAnimationConfig : ScriptableObject
    {
        [System.Serializable]
        public class Entry
        {
            public string memberName;
            public RuntimeAnimatorController controller;
        }

        public List<Entry> entries = new List<Entry>();

        public RuntimeAnimatorController GetController(string memberName)
        {
            foreach (var e in entries)
                if (e.memberName == memberName)
                    return e.controller;
            return null;
        }
    }
}
